### ISSUE TITLE
Re-rendering a form with validation errors results in blank fields

### ISSUE THREAD

**Issue by georgebrock** [danni/django-postgres-composite-types#18]
When a form using a composite type widget is used with a generic form view (e.g. `django.views.generic.UpdateView`, or from the Django admin site), and the form has validation errors, the widgets that make up the composite type will be rendered without their values.

The issue seems to be that the `CompositeTypeWidget.render` method uses [`getattr(value, subname, None)`][1] to retrieve the values for the individual fields. This fails because when we're rendering the form with validation errors `value` is a `dict`, and not an instance of a subclass of `CompositeType` (as it is when we're rendering the form without errors).

[1]: https://github.com/danni/django-postgres-composite-types/blob/0b6474e32e77cb8108c7e67d2524feb7b7e433d7/postgres_composite_types/forms.py#L186-L188

**Comment by danni** [comment]
Hi George, are you able to supply a test case for this issue? I have not had this issue and I'm wondering if there's something different in the way that you're using it.

**Comment by georgebrock** [comment]
Hi @danni. Thanks for making such a useful addition to Django, and for the quick reply on the issue!

I've put together a minimal Django app that demonstrates the issue: https://github.com/georgebrock/django-postgres-composite-types-issue-18

I also tried to add a test to this project's test suite, but I had trouble getting the suite to run. The issues I was hitting there seemed to be related to Django initialisation, so it's possible this is a Django 2.0 compatibility thing.

**Comment by georgebrock** [comment]
Thanks for this!

**Comment by timheap** [comment]
The fixes for this issue and #17, have been released in [v0.4.1 on PyPI](https://pypi.python.org/pypi/django-postgres-composite-types/0.4.1).
