### ISSUE TITLE
django admin form

### ISSUE THREAD

**Issue by mehdipourfar** [danni/django-postgres-composite-types#26]
Widget is created correctly inside django admin, but save doesn't work.

**Comment by mehdipourfar** [comment]
I have fix it and created a pull request.
[implement value_omitted_from_data function inside widget](https://github.com/danni/django-postgres-composite-types/pull/25/commits/b0a90ec1c3c46dca74173b3d6d403b935e51e9b2)

**Comment by danni** [comment]
Closed by #25
